version: "3"

networks:
  backend:
    external: false
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend
  expiry:
    image: expiry:1.0
    container_name: expiry
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mongodb